name: 香橙派5

on:
  workflow_dispatch:
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: 纳西妲小脚丫子炫我嘴里！
      run: |
        sudo chmod +x compile.sh
        echo "current_time=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV
    - name: 编译【香橙派5】最小化镜像
      run: |
        ./compile.sh \
        BOARD=orangepi5 \
        BRANCH=edge \
        RELEASE=focal \
        BUILD_MINIMAL=yes \
        BUILD_DESKTOP=no \
        KERNEL_CONFIGURE=no \
    - name: 压缩镜像
      run: |
        sudo tar -cJf build_$current_time.tar.xz output/images
    - name: 安装 AWS CLI
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install
        aws --version
    - name: 配置 AWS CLI
      run: |
        aws configure set aws_access_key_id githubAction
        aws configure set aws_secret_access_key xiaohuihui666
        aws configure set region us-east-1
    - name: 上传文件到 S3
      run: |
        s3url="https://open-94a11d64-9ef0-4eb9-ba56-0a4b595ab9d1-s3.saturn.xxyy.co:8443/armbian/build/orangepi5/build_${current_time}.tar.xz"
        echo "Endpoint is: $s3url"
        aws s3 cp build.tar.xz $s3url
    - name: 文件导出到 Github
      uses: actions/upload-artifact@v2
      with:
        name: build_${current_time}
        path: output/images/
